# Generated by Django 5.0 on 2024-01-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms_app', '0002_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fees_allotted',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='fees_paid',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending')], max_length=10, null=True),
        ),
    ]
