# Generated by Django 5.0 on 2024-01-03 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms_app', '0003_post_fees_allotted_post_fees_paid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_open', models.IntegerField()),
                ('type_obc', models.IntegerField(null=True)),
                ('type_obc_min', models.IntegerField(null=True)),
                ('type_vj', models.IntegerField(null=True)),
                ('type_vj_min', models.IntegerField(null=True)),
                ('type_nt', models.IntegerField(null=True)),
                ('type_nt_min', models.IntegerField(null=True)),
                ('type_sbc', models.IntegerField(null=True)),
                ('type_sbc_min', models.IntegerField(null=True)),
                ('type_sc', models.IntegerField(null=True)),
                ('type_st', models.IntegerField(null=True)),
                ('type_pwd', models.IntegerField(null=True)),
                ('type_rcsms', models.IntegerField(null=True)),
                ('type_ews', models.IntegerField(null=True)),
                ('type_sebc', models.IntegerField(null=True)),
                ('type_tfws', models.IntegerField(null=True)),
                ('type_jk', models.IntegerField(null=True)),
                ('type_ne', models.IntegerField(null=True)),
                ('type_pmsss', models.IntegerField(null=True)),
                ('type_ciwg', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=10)),
                ('fee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fms_app.fee')),
            ],
        ),
    ]
